# Generated by Django 5.0.1 on 2024-03-24 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id_doc', models.AutoField(primary_key=True, serialize=False)),
                ('nom_doc', models.CharField(max_length=60)),
                ('consult_doc', models.CharField(max_length=30)),
                ('tarifa_doc', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_espec', models.AutoField(primary_key=True, serialize=False)),
                ('nom_espec', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id_sec', models.AutoField(primary_key=True, serialize=False)),
                ('nom_sec', models.CharField(max_length=60)),
                ('email_sec', models.CharField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id_seg', models.AutoField(primary_key=True, serialize=False)),
                ('nom_seg', models.CharField(max_length=30)),
                ('tarifa_seg', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usu', models.AutoField(primary_key=True, serialize=False)),
                ('email_usu', models.CharField(max_length=254)),
                ('pass_usu', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_doc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medical.doctor')),
                ('id_espec', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medical.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_doc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medical.doctor')),
                ('id_sec', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medical.secretaria')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_pac', models.AutoField(primary_key=True, serialize=False)),
                ('nom_pac', models.CharField(max_length=60)),
                ('edad_pac', models.SmallIntegerField()),
                ('sexo_pac', models.CharField(max_length=2)),
                ('email_pac', models.CharField(max_length=254)),
                ('dni_pac', models.CharField(max_length=11)),
                ('tel_per_pac', models.CharField(max_length=11)),
                ('tel_dom_pac', models.CharField(max_length=11, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_seg', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medical.seguro')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Paciente',
            fields=[
                ('is_usu_pac', models.AutoField(primary_key=True, serialize=False)),
                ('id_pac', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medical.paciente')),
                ('id_usu', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medical.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Secretaria',
            fields=[
                ('is_usu_sec', models.AutoField(primary_key=True, serialize=False)),
                ('id_sec', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medical.secretaria')),
                ('id_usu', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medical.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_sol', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_sol', models.DateField()),
                ('motivo_sol', models.TextField(null=True)),
                ('estado_sol', models.SmallIntegerField(choices=[(0, 'Pendiente'), (1, 'Confirmada'), (2, 'Finalizada')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_doc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medical.doctor')),
                ('is_usu_pac', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medical.usuario_paciente')),
                ('is_usu_sec', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medical.usuario_secretaria')),
            ],
        ),
    ]
